### ISSUE TITLE
[Bug] Internal table of contents broken.

### ISSUE THREAD

**Issue by ChaoticWyrme** [danmolloy/omnibuser#1]
The table of contents you open in a menu is broken. If you try to navigate to a chapter from it, it just goes to the end of the book. I had this issue generating epub files from spacebattles/sufficient-velocity.

**Comment by danmolloy** [comment]
Hi ChaoticWyrme,

I wasn't able to reproduce this issue in Calibre. Can you please tell me what device and software you are using to view the epub, and if possible upload the specific epub you're having problems with?

Thanks.
