### ISSUE TITLE
Undefined Method error when trying to Get from Sufficient Velocity

### ISSUE THREAD

**Issue by ABZB** [danmolloy/omnibuser#10]
It is reporting the following error:

ERROR: undefined method `text' for nil:NilClass

I think they updated their website again.

**Comment by kemayo** [comment]
If it'd be helpful, you could extract most of the changed selectors from my own update over here: https://github.com/kemayo/leech/commit/3443304ab10692670beb6457919948590b1f3b19

**Comment by danmolloy** [comment]
Yup, SV did a big update.

@kemayo That's super helpful, thanks so much!

Hopefully I'll time this weekend to sort things out.

**Comment by pokeball99** [comment]
> ERROR: undefined method `value' for nil:NilClass
shows up now with the latest commits for SV:

https://forums.sufficientvelocity.com/threads/a-slime-quest.23206
https://forums.sufficientvelocity.com/threads/puella-magi-adfligo-systema.2538/
were the two threads that were done that resulted on this, using the PDF output

**Comment by danmolloy** [comment]
Site has been updated to scrape from the new SV.

@pokeball99 That issue should also be fixed - some extra steps need to be taken when scraping stories with more than ~90 chapters.

Please let me know if you encounter any more issues.

**Comment by kemayo** [comment]
@danmolloy a tip I worked out for mine — threadmarks means reader-mode is present. Writing the parser to just slurp up an entire thread in reader mode makes everything much faster and simpler, as you don’t need to care about using the API to load the collapsed threadmarks or requesting posts individually. I also don’t get throttled by SV any more. :D
