### ISSUE TITLE
"Insufficient Privilege" for SV,SB,FF, etc

### ISSUE THREAD

**Issue by pokeball99** [danmolloy/omnibuser#11]
`ERROR: PG::InsufficientPrivilege: ERROR: permission denied for relation requests : INSERT INTO "requests" ("url", "created_at", "updated_at", "status", "extension", "strategy", "recent_number") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"`

**Comment by danmolloy** [comment]
Hey this should be fixed now - had to do some emergency database
maintenance!

**Comment by pokeball99** [comment]
can confirm things are back in working order, closing this issue.
