### ISSUE TITLE
503 HTTP service error on SB/SV after last update

### ISSUE THREAD

**Issue by dakswiggin** [danmolloy/omnibuser#23]
Over last 3 days (since Xenforo2 parser update for SB) Omnibuser most of time (service worked ok for me for couple of hours over last days) returns 
'error: 503 => Net::HTTPServiceUnavailable for *story link*/threadmarks -- unhandled response' 
both for SpaceBattles and SufficientVelocity.

**Comment by danmolloy** [comment]
Hey thanks for letting me know! I think it's fixed now.

**Comment by danmolloy** [comment]
Thanks!

Just pushed an updated that should address this issue.

**Comment by dakswiggin** [comment]
Thanks, works perfect now!
